{% set python_min = '3.11' %}
{% set name = "specialist" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/specialist-{{ version }}.tar.gz
  sha256: bad93e2cdbc1f123c2161b14163ef66cef4113ea708f437751288a4ab221115d

build:
  entry_points:
    - specialist=specialist:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - specialist
  commands:
    - pip check
    - specialist --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/brandtbucher/specialist
  summary: Visualize CPython 3.11's specializing, adaptive interpreter.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
